/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XAny } from './xAny';


/**
 * An asset named SmoreIngredient
 */
export interface SmoreIngredient {
    /**
     * The class identifier for this type
     */
    _class?: string;
    /**
     * The instance identifier for this type
     */
    ingredientId: string;
    type: SmoreIngredient.TypeEnum;
    brand: string;
    /**
     * The identifier of an instance of smore
     */
    smore?: XAny;
}
export namespace SmoreIngredient {
    export type TypeEnum = 'GRAHAM_CRACKER' | 'MARSHMALLOW' | 'CHOCOLATE';
    export const TypeEnum = {
        GRAHAMCRACKER: 'GRAHAM_CRACKER' as TypeEnum,
        MARSHMALLOW: 'MARSHMALLOW' as TypeEnum,
        CHOCOLATE: 'CHOCOLATE' as TypeEnum
    }
}
